using System;
using System.Collections.Generic;

#nullable disable

namespace DPLK.Models
{
    public partial class RfTableExt
    {
        public string Tablename { get; set; }
        public string PrimaryKey { get; set; }
        public string ReadonlyField { get; set; }
        public string HiddenField { get; set; }
        public string AutogeneratedField { get; set; }
        public string SubmitSp { get; set; }
        public string SubmitSpField { get; set; }
    }
}
